package com.jlqr.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAttachmentInfo<M extends BaseAttachmentInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAttachmentName(java.lang.String attachmentName) {
		set("attachment_name", attachmentName);
		return (M)this;
	}

	public java.lang.String getAttachmentName() {
		return getStr("attachment_name");
	}

	public M setAttachmentPath(java.lang.String attachmentPath) {
		set("attachment_path", attachmentPath);
		return (M)this;
	}

	public java.lang.String getAttachmentPath() {
		return getStr("attachment_path");
	}

	public M setAttachmentTime(java.util.Date attachmentTime) {
		set("attachment_time", attachmentTime);
		return (M)this;
	}

	public java.util.Date getAttachmentTime() {
		return get("attachment_time");
	}

	public M setBindId(java.lang.Integer bindId) {
		set("bind_id", bindId);
		return (M)this;
	}

	public java.lang.Integer getBindId() {
		return getInt("bind_id");
	}

}
