package com.jlqr.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseItemInfo<M extends BaseItemInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setItemName(java.lang.String itemName) {
		set("item_name", itemName);
		return (M)this;
	}

	public java.lang.String getItemName() {
		return getStr("item_name");
	}

	public M setItemStart(java.util.Date itemStart) {
		set("item_start", itemStart);
		return (M)this;
	}

	public java.util.Date getItemStart() {
		return get("item_start");
	}

	public M setItemEnd(java.util.Date itemEnd) {
		set("item_end", itemEnd);
		return (M)this;
	}

	public java.util.Date getItemEnd() {
		return get("item_end");
	}

	public M setItemBrief(java.lang.String itemBrief) {
		set("item_brief", itemBrief);
		return (M)this;
	}

	public java.lang.String getItemBrief() {
		return getStr("item_brief");
	}

	public M setItemDuty(java.lang.String itemDuty) {
		set("item_duty", itemDuty);
		return (M)this;
	}

	public java.lang.String getItemDuty() {
		return getStr("item_duty");
	}

	public M setEmployId(java.lang.Integer employId) {
		set("employ_id", employId);
		return (M)this;
	}

	public java.lang.Integer getEmployId() {
		return getInt("employ_id");
	}

}
