package com.jlqr.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEmployInfo<M extends BaseEmployInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setEmployName(java.lang.String employName) {
		set("employ_name", employName);
		return (M)this;
	}

	public java.lang.String getEmployName() {
		return getStr("employ_name");
	}

	public M setEmploySex(java.lang.Integer employSex) {
		set("employ_sex", employSex);
		return (M)this;
	}

	public java.lang.Integer getEmploySex() {
		return getInt("employ_sex");
	}

	public M setEmployAge(java.lang.Integer employAge) {
		set("employ_age", employAge);
		return (M)this;
	}

	public java.lang.Integer getEmployAge() {
		return getInt("employ_age");
	}

	public M setEmployPhone(java.lang.String employPhone) {
		set("employ_phone", employPhone);
		return (M)this;
	}

	public java.lang.String getEmployPhone() {
		return getStr("employ_phone");
	}

	public M setEmployQq(java.lang.String employQq) {
		set("employ_qq", employQq);
		return (M)this;
	}

	public java.lang.String getEmployQq() {
		return getStr("employ_qq");
	}

	public M setEmployBirthday(java.lang.Long employBirthday) {
		set("employ_birthday", employBirthday);
		return (M)this;
	}

	public java.lang.Long getEmployBirthday() {
		return getLong("employ_birthday");
	}

	public M setEmployMarrage(java.lang.Integer employMarrage) {
		set("employ_marrage", employMarrage);
		return (M)this;
	}

	public java.lang.Integer getEmployMarrage() {
		return getInt("employ_marrage");
	}

	public M setEmployNativeplace(java.lang.String employNativeplace) {
		set("employ_nativeplace", employNativeplace);
		return (M)this;
	}

	public java.lang.String getEmployNativeplace() {
		return getStr("employ_nativeplace");
	}

	public M setEmployDomicile(java.lang.String employDomicile) {
		set("employ_domicile", employDomicile);
		return (M)this;
	}

	public java.lang.String getEmployDomicile() {
		return getStr("employ_domicile");
	}

	public M setEmployPolitics(java.lang.String employPolitics) {
		set("employ_politics", employPolitics);
		return (M)this;
	}

	public java.lang.String getEmployPolitics() {
		return getStr("employ_politics");
	}

	public M setEmployIdentityCard(java.lang.String employIdentityCard) {
		set("employ_identity_card", employIdentityCard);
		return (M)this;
	}

	public java.lang.String getEmployIdentityCard() {
		return getStr("employ_identity_card");
	}

	public M setEmployHealth(java.lang.String employHealth) {
		set("employ_health", employHealth);
		return (M)this;
	}

	public java.lang.String getEmployHealth() {
		return getStr("employ_health");
	}

	public M setEmployBloodType(java.lang.String employBloodType) {
		set("employ_blood_type", employBloodType);
		return (M)this;
	}

	public java.lang.String getEmployBloodType() {
		return getStr("employ_blood_type");
	}

	public M setEmployEmail(java.lang.String employEmail) {
		set("employ_email", employEmail);
		return (M)this;
	}

	public java.lang.String getEmployEmail() {
		return getStr("employ_email");
	}

	public M setEmployGraduation(java.lang.String employGraduation) {
		set("employ_graduation", employGraduation);
		return (M)this;
	}

	public java.lang.String getEmployGraduation() {
		return getStr("employ_graduation");
	}

	public M setEmploySpeciality(java.lang.String employSpeciality) {
		set("employ_speciality", employSpeciality);
		return (M)this;
	}

	public java.lang.String getEmploySpeciality() {
		return getStr("employ_speciality");
	}

	public M setEmployEducationId(java.lang.Integer employEducationId) {
		set("employ_education_id", employEducationId);
		return (M)this;
	}

	public java.lang.Integer getEmployEducationId() {
		return getInt("employ_education_id");
	}

	public M setEmployDegreeId(java.lang.Integer employDegreeId) {
		set("employ_degree_id", employDegreeId);
		return (M)this;
	}

	public java.lang.Integer getEmployDegreeId() {
		return getInt("employ_degree_id");
	}

	public M setEmployLanguageId(java.lang.Integer employLanguageId) {
		set("employ_language_id", employLanguageId);
		return (M)this;
	}

	public java.lang.Integer getEmployLanguageId() {
		return getInt("employ_language_id");
	}

	public M setEmployWsk(java.lang.String employWsk) {
		set("employ_wsk", employWsk);
		return (M)this;
	}

	public java.lang.String getEmployWsk() {
		return getStr("employ_wsk");
	}

	public M setEmployDiploma(java.lang.String employDiploma) {
		set("employ_diploma", employDiploma);
		return (M)this;
	}

	public java.lang.String getEmployDiploma() {
		return getStr("employ_diploma");
	}

	public M setEmployDossierPlace(java.lang.String employDossierPlace) {
		set("employ_dossier_place", employDossierPlace);
		return (M)this;
	}

	public java.lang.String getEmployDossierPlace() {
		return getStr("employ_dossier_place");
	}

	public M setEmployJobTime(java.lang.Long employJobTime) {
		set("employ_job_time", employJobTime);
		return (M)this;
	}

	public java.lang.Long getEmployJobTime() {
		return getLong("employ_job_time");
	}

	public M setEmployJoinTime(java.lang.Long employJoinTime) {
		set("employ_join_time", employJoinTime);
		return (M)this;
	}

	public java.lang.Long getEmployJoinTime() {
		return getLong("employ_join_time");
	}

	public M setEmployImg(java.lang.String employImg) {
		set("employ_img", employImg);
		return (M)this;
	}

	public java.lang.String getEmployImg() {
		return getStr("employ_img");
	}

	public M setEmployJobNumber(java.lang.String employJobNumber) {
		set("employ_job_number", employJobNumber);
		return (M)this;
	}

	public java.lang.String getEmployJobNumber() {
		return getStr("employ_job_number");
	}

	public M setEmployIdPath(java.lang.String employIdPath) {
		set("employ_id_path", employIdPath);
		return (M)this;
	}

	public java.lang.String getEmployIdPath() {
		return getStr("employ_id_path");
	}

}
