package com.jlqr.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEducationInfo<M extends BaseEducationInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSchoolName(java.lang.String schoolName) {
		set("school_name", schoolName);
		return (M)this;
	}

	public java.lang.String getSchoolName() {
		return getStr("school_name");
	}

	public M setMajor(java.lang.String major) {
		set("major", major);
		return (M)this;
	}

	public java.lang.String getMajor() {
		return getStr("major");
	}

	public M setEducationStart(java.util.Date educationStart) {
		set("education_start", educationStart);
		return (M)this;
	}

	public java.util.Date getEducationStart() {
		return get("education_start");
	}

	public M setEducationEnd(java.util.Date educationEnd) {
		set("education_end", educationEnd);
		return (M)this;
	}

	public java.util.Date getEducationEnd() {
		return get("education_end");
	}

	public M setEmployId(java.lang.Integer employId) {
		set("employ_id", employId);
		return (M)this;
	}

	public java.lang.Integer getEmployId() {
		return getInt("employ_id");
	}

}
