package com.jlqr.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLoginInfo<M extends BaseLoginInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
		return (M)this;
	}

	public java.lang.String getLoginName() {
		return getStr("login_name");
	}

	public M setLoginPwd(java.lang.String loginPwd) {
		set("login_pwd", loginPwd);
		return (M)this;
	}

	public java.lang.String getLoginPwd() {
		return getStr("login_pwd");
	}

	public M setLoginImg(java.lang.String loginImg) {
		set("login_img", loginImg);
		return (M)this;
	}

	public java.lang.String getLoginImg() {
		return getStr("login_img");
	}

	public M setLoginState(java.lang.Integer loginState) {
		set("login_state", loginState);
		return (M)this;
	}

	public java.lang.Integer getLoginState() {
		return getInt("login_state");
	}

	public M setDepartmentId(java.lang.Integer departmentId) {
		set("department_id", departmentId);
		return (M)this;
	}

	public java.lang.Integer getDepartmentId() {
		return getInt("department_id");
	}

	public M setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}

	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

	public M setCreateTime(java.lang.Long createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.lang.Long getCreateTime() {
		return getLong("create_time");
	}

}
