package com.jlqr.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("dictionary", "id", Dictionary.class);
		arp.addMapping("employ_info", "id", EmployInfo.class);
		arp.addMapping("login_info", "id", LoginInfo.class);
		arp.addMapping("power_info", "id", PowerInfo.class);
		arp.addMapping("project_info", "id", ProjectInfo.class);
		arp.addMapping("role_info", "id", RoleInfo.class);
	}
}

