package com.jlqr.common.model;

import com.jlqr.common.model.base.BaseEmployInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmployInfo extends BaseEmployInfo<EmployInfo> {
	public static final EmployInfo dao = new EmployInfo().dao();
}
