package com.jlqr.common.model;

import com.jlqr.common.model.base.BaseItemInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ItemInfo extends BaseItemInfo<ItemInfo> {
	public static final ItemInfo dao = new ItemInfo().dao();
}
