package com.jlqr.common.model;

import com.jlqr.common.model.base.BasePersonnelContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonnelContract extends BasePersonnelContract<PersonnelContract> {
	public static final PersonnelContract dao = new PersonnelContract().dao();
}
