package com.jlqr.common.model;

import com.jlqr.common.model.base.BaseProjectInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectInfo extends BaseProjectInfo<ProjectInfo> {
	public static final ProjectInfo dao = new ProjectInfo().dao();
}
