package com.jlqr.common.model;

import com.jlqr.common.model.base.BaseReimburseInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReimburseInfo extends BaseReimburseInfo<ReimburseInfo> {
	public static final ReimburseInfo dao = new ReimburseInfo().dao();
}
