package com.jlqr.common.model;

import com.jlqr.common.model.base.BaseRoleInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleInfo extends BaseRoleInfo<RoleInfo> {
	public static final RoleInfo dao = new RoleInfo().dao();
}
