package com.jlqr.common.model;

import com.jlqr.common.model.base.BaseWorkInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkInfo extends BaseWorkInfo<WorkInfo> {
	public static final WorkInfo dao = new WorkInfo().dao();
}
