package com.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePublicManInfo<M extends BasePublicManInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPublicName(java.lang.String publicName) {
		set("public_name", publicName);
		return (M)this;
	}

	public java.lang.String getPublicName() {
		return getStr("public_name");
	}

	public M setPublicAge(java.lang.Integer publicAge) {
		set("public_age", publicAge);
		return (M)this;
	}

	public java.lang.Integer getPublicAge() {
		return getInt("public_age");
	}

	public M setPublicProverbs(java.lang.String publicProverbs) {
		set("public_proverbs", publicProverbs);
		return (M)this;
	}

	public java.lang.String getPublicProverbs() {
		return getStr("public_proverbs");
	}

	public M setPublicEvaluation(java.lang.String publicEvaluation) {
		set("public_evaluation", publicEvaluation);
		return (M)this;
	}

	public java.lang.String getPublicEvaluation() {
		return getStr("public_evaluation");
	}

	public M setPublicIntroduce(java.lang.String publicIntroduce) {
		set("public_introduce", publicIntroduce);
		return (M)this;
	}

	public java.lang.String getPublicIntroduce() {
		return getStr("public_introduce");
	}

	public M setPublicIstop(java.lang.Integer publicIstop) {
		set("public_isTop", publicIstop);
		return (M)this;
	}

	public java.lang.Integer getPublicIstop() {
		return getInt("public_isTop");
	}

	public M setPublicImg(java.lang.String publicImg) {
		set("public_img", publicImg);
		return (M)this;
	}

	public java.lang.String getPublicImg() {
		return getStr("public_img");
	}

	public M setPublicOpenSize(java.lang.Integer publicOpenSize) {
		set("public_open_size", publicOpenSize);
		return (M)this;
	}

	public java.lang.Integer getPublicOpenSize() {
		return getInt("public_open_size");
	}

	public M setPublicCreateTime(java.util.Date publicCreateTime) {
		set("public_create_time", publicCreateTime);
		return (M)this;
	}

	public java.util.Date getPublicCreateTime() {
		return get("public_create_time");
	}

	public M setPublicState(java.lang.Integer publicState) {
		set("public_state", publicState);
		return (M)this;
	}

	public java.lang.Integer getPublicState() {
		return getInt("public_state");
	}

	public M setPublicContent(java.lang.String publicContent) {
		set("public_content", publicContent);
		return (M)this;
	}

	public java.lang.String getPublicContent() {
		return getStr("public_content");
	}

}
