package com.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProjectInfo<M extends BaseProjectInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProjectNumber(java.lang.String projectNumber) {
		set("project_number", projectNumber);
		return (M)this;
	}

	public java.lang.String getProjectNumber() {
		return getStr("project_number");
	}

	public M setProjectState(java.lang.Integer projectState) {
		set("project_state", projectState);
		return (M)this;
	}

	public java.lang.Integer getProjectState() {
		return getInt("project_state");
	}

	public M setProjectCreateTime(java.util.Date projectCreateTime) {
		set("project_create_time", projectCreateTime);
		return (M)this;
	}

	public java.util.Date getProjectCreateTime() {
		return get("project_create_time");
	}

	public M setProjectUpdateTime(java.util.Date projectUpdateTime) {
		set("project_update_time", projectUpdateTime);
		return (M)this;
	}

	public java.util.Date getProjectUpdateTime() {
		return get("project_update_time");
	}

	public M setProjectUnit(java.lang.Integer projectUnit) {
		set("project_unit", projectUnit);
		return (M)this;
	}

	public java.lang.Integer getProjectUnit() {
		return getInt("project_unit");
	}

	public M setProjectCharge(java.lang.Integer projectCharge) {
		set("project_charge", projectCharge);
		return (M)this;
	}

	public java.lang.Integer getProjectCharge() {
		return getInt("project_charge");
	}

	public M setProjectCollector(java.lang.Integer projectCollector) {
		set("project_collector", projectCollector);
		return (M)this;
	}

	public java.lang.Integer getProjectCollector() {
		return getInt("project_collector");
	}

	public M setProjectDepartment(java.lang.Integer projectDepartment) {
		set("project_department", projectDepartment);
		return (M)this;
	}

	public java.lang.Integer getProjectDepartment() {
		return getInt("project_department");
	}

	public M setProjectName(java.lang.String projectName) {
		set("project_name", projectName);
		return (M)this;
	}

	public java.lang.String getProjectName() {
		return getStr("project_name");
	}

	public M setProjectBudget(java.lang.Integer projectBudget) {
		set("project_budget", projectBudget);
		return (M)this;
	}

	public java.lang.Integer getProjectBudget() {
		return getInt("project_budget");
	}

	public M setProjectSituation(java.lang.String projectSituation) {
		set("project_situation", projectSituation);
		return (M)this;
	}

	public java.lang.String getProjectSituation() {
		return getStr("project_situation");
	}

	public M setProjectCapitalSituation(java.lang.String projectCapitalSituation) {
		set("project_capital_situation", projectCapitalSituation);
		return (M)this;
	}

	public java.lang.String getProjectCapitalSituation() {
		return getStr("project_capital_situation");
	}

	public M setProjectContact(java.lang.Integer projectContact) {
		set("project_contact", projectContact);
		return (M)this;
	}

	public java.lang.Integer getProjectContact() {
		return getInt("project_contact");
	}

	public M setProjectChargeGuardian(java.lang.Integer projectChargeGuardian) {
		set("project_charge_guardian", projectChargeGuardian);
		return (M)this;
	}

	public java.lang.Integer getProjectChargeGuardian() {
		return getInt("project_charge_guardian");
	}

	public M setProjectChargeLeader(java.lang.Integer projectChargeLeader) {
		set("project_charge_leader", projectChargeLeader);
		return (M)this;
	}

	public java.lang.Integer getProjectChargeLeader() {
		return getInt("project_charge_leader");
	}

	public M setProjectRemark(java.lang.String projectRemark) {
		set("project_remark", projectRemark);
		return (M)this;
	}

	public java.lang.String getProjectRemark() {
		return getStr("project_remark");
	}

	public M setProjectType(java.lang.Integer projectType) {
		set("project_type", projectType);
		return (M)this;
	}

	public java.lang.Integer getProjectType() {
		return getInt("project_type");
	}

	public M setProjectPriority(java.lang.Integer projectPriority) {
		set("project_priority", projectPriority);
		return (M)this;
	}

	public java.lang.Integer getProjectPriority() {
		return getInt("project_priority");
	}

	public M setProjectPushExpenses(java.lang.Integer projectPushExpenses) {
		set("project_push_expenses", projectPushExpenses);
		return (M)this;
	}

	public java.lang.Integer getProjectPushExpenses() {
		return getInt("project_push_expenses");
	}

	public M setProjectPushExcess(java.lang.String projectPushExcess) {
		set("project_push_excess", projectPushExcess);
		return (M)this;
	}

	public java.lang.String getProjectPushExcess() {
		return getStr("project_push_excess");
	}

	public M setProjectSource(java.lang.Integer projectSource) {
		set("project_source", projectSource);
		return (M)this;
	}

	public java.lang.Integer getProjectSource() {
		return getInt("project_source");
	}

	public M setProjectBidTime(java.util.Date projectBidTime) {
		set("project_bid_time", projectBidTime);
		return (M)this;
	}

	public java.util.Date getProjectBidTime() {
		return get("project_bid_time");
	}

	public M setProjectMoney(java.lang.Integer projectMoney) {
		set("project_money", projectMoney);
		return (M)this;
	}

	public java.lang.Integer getProjectMoney() {
		return getInt("project_money");
	}

	public M setProjectCollectionPlanRemark(java.lang.String projectCollectionPlanRemark) {
		set("project_collection_plan_remark", projectCollectionPlanRemark);
		return (M)this;
	}

	public java.lang.String getProjectCollectionPlanRemark() {
		return getStr("project_collection_plan_remark");
	}

	public M setProjectPaymentPlanRemark(java.lang.String projectPaymentPlanRemark) {
		set("project_payment_plan_remark", projectPaymentPlanRemark);
		return (M)this;
	}

	public java.lang.String getProjectPaymentPlanRemark() {
		return getStr("project_payment_plan_remark");
	}

	public M setProjectApplyCount(java.lang.Integer projectApplyCount) {
		set("project_apply_count", projectApplyCount);
		return (M)this;
	}

	public java.lang.Integer getProjectApplyCount() {
		return getInt("project_apply_count");
	}

}
