package com.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActivityComement<M extends BaseActivityComement<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
		return (M)this;
	}

	public java.lang.Integer getActivityId() {
		return getInt("activity_id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setContentTime(java.util.Date contentTime) {
		set("content_time", contentTime);
		return (M)this;
	}

	public java.util.Date getContentTime() {
		return get("content_time");
	}

}
