package com.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserUsername(java.lang.String userUsername) {
		set("user_username", userUsername);
		return (M)this;
	}

	public java.lang.String getUserUsername() {
		return getStr("user_username");
	}

	public M setUserNickname(java.lang.String userNickname) {
		set("user_nickname", userNickname);
		return (M)this;
	}

	public java.lang.String getUserNickname() {
		return getStr("user_nickname");
	}

	public M setUserPassword(java.lang.String userPassword) {
		set("user_password", userPassword);
		return (M)this;
	}

	public java.lang.String getUserPassword() {
		return getStr("user_password");
	}

	public M setUserAge(java.lang.Integer userAge) {
		set("user_age", userAge);
		return (M)this;
	}

	public java.lang.Integer getUserAge() {
		return getInt("user_age");
	}

	public M setUserSex(java.lang.Integer userSex) {
		set("user_sex", userSex);
		return (M)this;
	}

	public java.lang.Integer getUserSex() {
		return getInt("user_sex");
	}

	public M setUserPhone(java.lang.String userPhone) {
		set("user_phone", userPhone);
		return (M)this;
	}

	public java.lang.String getUserPhone() {
		return getStr("user_phone");
	}

	public M setUserEmail(java.lang.String userEmail) {
		set("user_email", userEmail);
		return (M)this;
	}

	public java.lang.String getUserEmail() {
		return getStr("user_email");
	}

	public M setUserIsRegister(java.lang.Integer userIsRegister) {
		set("user_is_register", userIsRegister);
		return (M)this;
	}

	public java.lang.Integer getUserIsRegister() {
		return getInt("user_is_register");
	}

	public M setUserCode(java.lang.String userCode) {
		set("user_code", userCode);
		return (M)this;
	}

	public java.lang.String getUserCode() {
		return getStr("user_code");
	}

	public M setUserIntegral(java.lang.Integer userIntegral) {
		set("user_integral", userIntegral);
		return (M)this;
	}

	public java.lang.Integer getUserIntegral() {
		return getInt("user_integral");
	}

	public M setUserPostNum(java.lang.Integer userPostNum) {
		set("user_post_num", userPostNum);
		return (M)this;
	}

	public java.lang.Integer getUserPostNum() {
		return getInt("user_post_num");
	}

	public M setUserCommentNum(java.lang.Integer userCommentNum) {
		set("user_comment_num", userCommentNum);
		return (M)this;
	}

	public java.lang.Integer getUserCommentNum() {
		return getInt("user_comment_num");
	}

	public M setUserRegisterTime(java.util.Date userRegisterTime) {
		set("user_register_time", userRegisterTime);
		return (M)this;
	}

	public java.util.Date getUserRegisterTime() {
		return get("user_register_time");
	}

	public M setUserActiveTime(java.util.Date userActiveTime) {
		set("user_active_time", userActiveTime);
		return (M)this;
	}

	public java.util.Date getUserActiveTime() {
		return get("user_active_time");
	}

	public M setUserImg(java.lang.String userImg) {
		set("user_img", userImg);
		return (M)this;
	}

	public java.lang.String getUserImg() {
		return getStr("user_img");
	}

	public M setUserScore(java.lang.Integer userScore) {
		set("user_score", userScore);
		return (M)this;
	}

	public java.lang.Integer getUserScore() {
		return getInt("user_score");
	}

	public M setIsAble(java.lang.Integer isAble) {
		set("is_able", isAble);
		return (M)this;
	}

	public java.lang.Integer getIsAble() {
		return getInt("is_able");
	}

}
