package com.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCarouseInfo<M extends BaseCarouseInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCarouseImg(java.lang.String carouseImg) {
		set("carouse_img", carouseImg);
		return (M)this;
	}

	public java.lang.String getCarouseImg() {
		return getStr("carouse_img");
	}

	public M setCarouseCreatetime(java.util.Date carouseCreatetime) {
		set("carouse_createtime", carouseCreatetime);
		return (M)this;
	}

	public java.util.Date getCarouseCreatetime() {
		return get("carouse_createtime");
	}

	public M setCarouseChagetime(java.util.Date carouseChagetime) {
		set("carouse_chagetime", carouseChagetime);
		return (M)this;
	}

	public java.util.Date getCarouseChagetime() {
		return get("carouse_chagetime");
	}

	public M setCarouseIstop(java.lang.Integer carouseIstop) {
		set("carouse_istop", carouseIstop);
		return (M)this;
	}

	public java.lang.Integer getCarouseIstop() {
		return getInt("carouse_istop");
	}

	public M setCarouseTitle(java.lang.String carouseTitle) {
		set("carouse_title", carouseTitle);
		return (M)this;
	}

	public java.lang.String getCarouseTitle() {
		return getStr("carouse_title");
	}

	public M setCarouseLink(java.lang.String carouseLink) {
		set("carouse_link", carouseLink);
		return (M)this;
	}

	public java.lang.String getCarouseLink() {
		return getStr("carouse_link");
	}

}
