package com.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseForumManagerInfo<M extends BaseForumManagerInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setManagerTitle(java.lang.String managerTitle) {
		set("manager_title", managerTitle);
		return (M)this;
	}

	public java.lang.String getManagerTitle() {
		return getStr("manager_title");
	}

	public M setManagerContent(java.lang.String managerContent) {
		set("manager_content", managerContent);
		return (M)this;
	}

	public java.lang.String getManagerContent() {
		return getStr("manager_content");
	}

	public M setManagerType(java.lang.Integer managerType) {
		set("manager_type", managerType);
		return (M)this;
	}

	public java.lang.Integer getManagerType() {
		return getInt("manager_type");
	}

	public M setManagerState(java.lang.Integer managerState) {
		set("manager_state", managerState);
		return (M)this;
	}

	public java.lang.Integer getManagerState() {
		return getInt("manager_state");
	}

	public M setManagerLink(java.lang.String managerLink) {
		set("manager_link", managerLink);
		return (M)this;
	}

	public java.lang.String getManagerLink() {
		return getStr("manager_link");
	}

	public M setManagerCreateTime(java.util.Date managerCreateTime) {
		set("manager_create_time", managerCreateTime);
		return (M)this;
	}

	public java.util.Date getManagerCreateTime() {
		return get("manager_create_time");
	}

}
