package com.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMangerInfo<M extends BaseMangerInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMangerName(java.lang.String mangerName) {
		set("manger_name", mangerName);
		return (M)this;
	}

	public java.lang.String getMangerName() {
		return getStr("manger_name");
	}

	public M setMangerSex(java.lang.Integer mangerSex) {
		set("manger_sex", mangerSex);
		return (M)this;
	}

	public java.lang.Integer getMangerSex() {
		return getInt("manger_sex");
	}

	public M setMangerAge(java.lang.Integer mangerAge) {
		set("manger_age", mangerAge);
		return (M)this;
	}

	public java.lang.Integer getMangerAge() {
		return getInt("manger_age");
	}

	public M setMangerPhone(java.lang.String mangerPhone) {
		set("manger_phone", mangerPhone);
		return (M)this;
	}

	public java.lang.String getMangerPhone() {
		return getStr("manger_phone");
	}

	public M setMangerQq(java.lang.String mangerQq) {
		set("manger_qq", mangerQq);
		return (M)this;
	}

	public java.lang.String getMangerQq() {
		return getStr("manger_qq");
	}

	public M setMangerBirthday(java.lang.String mangerBirthday) {
		set("manger_birthday", mangerBirthday);
		return (M)this;
	}

	public java.lang.String getMangerBirthday() {
		return getStr("manger_birthday");
	}

	public M setMangerMarrage(java.lang.Integer mangerMarrage) {
		set("manger_marrage", mangerMarrage);
		return (M)this;
	}

	public java.lang.Integer getMangerMarrage() {
		return getInt("manger_marrage");
	}

	public M setMangerNativeplace(java.lang.String mangerNativeplace) {
		set("manger_nativeplace", mangerNativeplace);
		return (M)this;
	}

	public java.lang.String getMangerNativeplace() {
		return getStr("manger_nativeplace");
	}

	public M setMangerDomicile(java.lang.String mangerDomicile) {
		set("manger_domicile", mangerDomicile);
		return (M)this;
	}

	public java.lang.String getMangerDomicile() {
		return getStr("manger_domicile");
	}

	public M setMangerPolitics(java.lang.String mangerPolitics) {
		set("manger_politics", mangerPolitics);
		return (M)this;
	}

	public java.lang.String getMangerPolitics() {
		return getStr("manger_politics");
	}

	public M setMangerIdentityCard(java.lang.String mangerIdentityCard) {
		set("manger_identity_card", mangerIdentityCard);
		return (M)this;
	}

	public java.lang.String getMangerIdentityCard() {
		return getStr("manger_identity_card");
	}

	public M setMangerHealth(java.lang.String mangerHealth) {
		set("manger_health", mangerHealth);
		return (M)this;
	}

	public java.lang.String getMangerHealth() {
		return getStr("manger_health");
	}

	public M setMangerBloodType(java.lang.String mangerBloodType) {
		set("manger_blood_type", mangerBloodType);
		return (M)this;
	}

	public java.lang.String getMangerBloodType() {
		return getStr("manger_blood_type");
	}

	public M setMangerEmail(java.lang.String mangerEmail) {
		set("manger_email", mangerEmail);
		return (M)this;
	}

	public java.lang.String getMangerEmail() {
		return getStr("manger_email");
	}

	public M setMangerGraduation(java.lang.String mangerGraduation) {
		set("manger_graduation", mangerGraduation);
		return (M)this;
	}

	public java.lang.String getMangerGraduation() {
		return getStr("manger_graduation");
	}

	public M setMangerSpeciality(java.lang.String mangerSpeciality) {
		set("manger_speciality", mangerSpeciality);
		return (M)this;
	}

	public java.lang.String getMangerSpeciality() {
		return getStr("manger_speciality");
	}

	public M setMangerEducationId(java.lang.Integer mangerEducationId) {
		set("manger_education_id", mangerEducationId);
		return (M)this;
	}

	public java.lang.Integer getMangerEducationId() {
		return getInt("manger_education_id");
	}

	public M setMangerDegreeId(java.lang.Integer mangerDegreeId) {
		set("manger_degree_id", mangerDegreeId);
		return (M)this;
	}

	public java.lang.Integer getMangerDegreeId() {
		return getInt("manger_degree_id");
	}

	public M setMangerLanguageId(java.lang.Integer mangerLanguageId) {
		set("manger_language_id", mangerLanguageId);
		return (M)this;
	}

	public java.lang.Integer getMangerLanguageId() {
		return getInt("manger_language_id");
	}

	public M setMangerWsk(java.lang.String mangerWsk) {
		set("manger_wsk", mangerWsk);
		return (M)this;
	}

	public java.lang.String getMangerWsk() {
		return getStr("manger_wsk");
	}

	public M setMangerDiploma(java.lang.String mangerDiploma) {
		set("manger_diploma", mangerDiploma);
		return (M)this;
	}

	public java.lang.String getMangerDiploma() {
		return getStr("manger_diploma");
	}

	public M setMangerDossierPlace(java.lang.String mangerDossierPlace) {
		set("manger_dossier_place", mangerDossierPlace);
		return (M)this;
	}

	public java.lang.String getMangerDossierPlace() {
		return getStr("manger_dossier_place");
	}

	public M setMangerJobTime(java.util.Date mangerJobTime) {
		set("manger_job_time", mangerJobTime);
		return (M)this;
	}

	public java.util.Date getMangerJobTime() {
		return get("manger_job_time");
	}

	public M setMangerJoinTime(java.util.Date mangerJoinTime) {
		set("manger_join_time", mangerJoinTime);
		return (M)this;
	}

	public java.util.Date getMangerJoinTime() {
		return get("manger_join_time");
	}

	public M setMangerImg(java.lang.String mangerImg) {
		set("manger_img", mangerImg);
		return (M)this;
	}

	public java.lang.String getMangerImg() {
		return getStr("manger_img");
	}

	public M setMangerJobNumber(java.lang.String mangerJobNumber) {
		set("manger_job_number", mangerJobNumber);
		return (M)this;
	}

	public java.lang.String getMangerJobNumber() {
		return getStr("manger_job_number");
	}

	public M setMangerIdPath(java.lang.String mangerIdPath) {
		set("manger_id_path", mangerIdPath);
		return (M)this;
	}

	public java.lang.String getMangerIdPath() {
		return getStr("manger_id_path");
	}

}
