package com.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActivityInfo<M extends BaseActivityInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setActivityTitle(java.lang.String activityTitle) {
		set("activity_title", activityTitle);
		return (M)this;
	}

	public java.lang.String getActivityTitle() {
		return getStr("activity_title");
	}

	public M setActivityAddr(java.lang.String activityAddr) {
		set("activity_addr", activityAddr);
		return (M)this;
	}

	public java.lang.String getActivityAddr() {
		return getStr("activity_addr");
	}

	public M setActivityBeginTime(java.util.Date activityBeginTime) {
		set("activity_begin_time", activityBeginTime);
		return (M)this;
	}

	public java.util.Date getActivityBeginTime() {
		return get("activity_begin_time");
	}

	public M setActivityEndTime(java.util.Date activityEndTime) {
		set("activity_end_time", activityEndTime);
		return (M)this;
	}

	public java.util.Date getActivityEndTime() {
		return get("activity_end_time");
	}

	public M setActivityEnrolStarttime(java.util.Date activityEnrolStarttime) {
		set("activity_enrol_starttime", activityEnrolStarttime);
		return (M)this;
	}

	public java.util.Date getActivityEnrolStarttime() {
		return get("activity_enrol_starttime");
	}

	public M setActivityEnrolEndtime(java.util.Date activityEnrolEndtime) {
		set("activity_enrol_endtime", activityEnrolEndtime);
		return (M)this;
	}

	public java.util.Date getActivityEnrolEndtime() {
		return get("activity_enrol_endtime");
	}

	public M setActivityEnrolTotal(java.lang.Integer activityEnrolTotal) {
		set("activity_enrol_total", activityEnrolTotal);
		return (M)this;
	}

	public java.lang.Integer getActivityEnrolTotal() {
		return getInt("activity_enrol_total");
	}

	public M setActivityContent(java.lang.String activityContent) {
		set("activity_content", activityContent);
		return (M)this;
	}

	public java.lang.String getActivityContent() {
		return getStr("activity_content");
	}

	public M setActivityState(java.lang.Integer activityState) {
		set("activity_state", activityState);
		return (M)this;
	}

	public java.lang.Integer getActivityState() {
		return getInt("activity_state");
	}

	public M setActivityHold(java.lang.Integer activityHold) {
		set("activity_hold", activityHold);
		return (M)this;
	}

	public java.lang.Integer getActivityHold() {
		return getInt("activity_hold");
	}

	public M setActivityType(java.lang.Integer activityType) {
		set("activity_type", activityType);
		return (M)this;
	}

	public java.lang.Integer getActivityType() {
		return getInt("activity_type");
	}

	public M setActivityFree(java.lang.Integer activityFree) {
		set("activity_free", activityFree);
		return (M)this;
	}

	public java.lang.Integer getActivityFree() {
		return getInt("activity_free");
	}

	public M setActivityCoverImg(java.lang.String activityCoverImg) {
		set("activity_cover_img", activityCoverImg);
		return (M)this;
	}

	public java.lang.String getActivityCoverImg() {
		return getStr("activity_cover_img");
	}

	public M setActivityIsRecomened(java.lang.Integer activityIsRecomened) {
		set("activity_is_recomened", activityIsRecomened);
		return (M)this;
	}

	public java.lang.Integer getActivityIsRecomened() {
		return getInt("activity_is_recomened");
	}

	public M setActivityIntroduce(java.lang.String activityIntroduce) {
		set("activity_introduce", activityIntroduce);
		return (M)this;
	}

	public java.lang.String getActivityIntroduce() {
		return getStr("activity_introduce");
	}

	public M setActivityCheckState(java.lang.Integer activityCheckState) {
		set("activity_check_state", activityCheckState);
		return (M)this;
	}

	public java.lang.Integer getActivityCheckState() {
		return getInt("activity_check_state");
	}

	public M setActivityChangeTime(java.util.Date activityChangeTime) {
		set("activity_change_time", activityChangeTime);
		return (M)this;
	}

	public java.util.Date getActivityChangeTime() {
		return get("activity_change_time");
	}

	public M setActivityAttendNum(java.lang.Integer activityAttendNum) {
		set("activity_attend_num", activityAttendNum);
		return (M)this;
	}

	public java.lang.Integer getActivityAttendNum() {
		return getInt("activity_attend_num");
	}

}
