package com.admin.common.model;

import com.admin.common.model.base.BaseActivityComement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActivityComement extends BaseActivityComement<ActivityComement> {
	public static final ActivityComement dao = new ActivityComement().dao();
}
