package com.admin.common.model;

import com.admin.common.model.base.BaseActivityUnit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActivityUnit extends BaseActivityUnit<ActivityUnit> {
	public static final ActivityUnit dao = new ActivityUnit().dao();
}
