package com.admin.common.model;

import com.admin.common.model.base.BaseActivityInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActivityInfo extends BaseActivityInfo<ActivityInfo> {
	public static final ActivityInfo dao = new ActivityInfo().dao();
	
}
