package com.admin.common.model;

import com.admin.common.model.base.BaseActivityComementInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActivityComementInfo extends BaseActivityComementInfo<ActivityComementInfo> {
	public static final ActivityComementInfo dao = new ActivityComementInfo().dao();
}
