package com.admin.common.model;

import com.admin.common.model.base.BaseAttachmentInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttachmentInfo extends BaseAttachmentInfo<AttachmentInfo> {
	public static final AttachmentInfo dao = new AttachmentInfo().dao();
}
