package com.admin.common.model;

import com.admin.common.model.base.BaseAttendInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttendInfo extends BaseAttendInfo<AttendInfo> {
	public static final AttendInfo dao = new AttendInfo().dao();
}
