package com.admin.common.model;

import com.admin.common.model.base.BaseCarouseInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarouseInfo extends BaseCarouseInfo<CarouseInfo> {
	public static final CarouseInfo dao = new CarouseInfo().dao();
}
