package com.admin.common.model;

import com.admin.common.model.base.BaseDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dictionary extends BaseDictionary<Dictionary> {
	public static final Dictionary dao = new Dictionary().dao();
}
