package com.admin.common.model;

import com.admin.common.model.base.BaseEducationInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EducationInfo extends BaseEducationInfo<EducationInfo> {
	public static final EducationInfo dao = new EducationInfo().dao();
}
