package com.admin.common.model;

import com.admin.common.model.base.BaseForumInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForumInfo extends BaseForumInfo<ForumInfo> {
	public static final ForumInfo dao = new ForumInfo().dao();
}
