package com.admin.common.model;

import com.admin.common.model.base.BaseForumComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForumComment extends BaseForumComment<ForumComment> {
	public static final ForumComment dao = new ForumComment().dao();
}
