package com.admin.common.model;

import com.admin.common.model.base.BaseForumChannel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForumChannel extends BaseForumChannel<ForumChannel> {
	public static final ForumChannel dao = new ForumChannel().dao();
}
