package com.admin.common.model;

import com.admin.common.model.base.BaseForumManagerInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForumManagerInfo extends BaseForumManagerInfo<ForumManagerInfo> {
	public static final ForumManagerInfo dao = new ForumManagerInfo().dao();
}
