package com.admin.common.model;

import com.admin.common.model.base.BaseLoginInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginInfo extends BaseLoginInfo<LoginInfo> {
	public static final LoginInfo dao = new LoginInfo().dao();
}
