package com.admin.common.model;

import com.admin.common.model.base.BaseMangerInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MangerInfo extends BaseMangerInfo<MangerInfo> {
	public static final MangerInfo dao = new MangerInfo().dao();
}
