package com.admin.common.model;

import com.admin.common.model.base.BaseNewInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewInfo extends BaseNewInfo<NewInfo> {
	public static final NewInfo dao = new NewInfo().dao();
}
