package com.admin.common.model;

import com.admin.common.model.base.BasePowerInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PowerInfo extends BasePowerInfo<PowerInfo> {
	public static final PowerInfo dao = new PowerInfo().dao();
}
