package com.admin.common.model;

import com.admin.common.model.base.BasePublicManInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PublicManInfo extends BasePublicManInfo<PublicManInfo> {
	public static final PublicManInfo dao = new PublicManInfo().dao();
}
