package com.admin.common.model;

import com.admin.common.model.base.BaseRoleInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleInfo extends BaseRoleInfo<RoleInfo> {
	public static final RoleInfo dao = new RoleInfo().dao();
}
