package com.admin.common.model;

import com.admin.common.model.base.BaseWikipediaInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WikipediaInfo extends BaseWikipediaInfo<WikipediaInfo> {
	public static final WikipediaInfo dao = new WikipediaInfo().dao();
}
